export const headers = [
  {
    title: 'Rank',
    align: 'start',
    sortable: false,
    key: 'rank',
    width: '65px',
  },
  { title: 'Main', align: 'start', key: 'main' },
  { title: 'HQ', align: 'start', key: 'hq' },
  { title: 'Type', align: 'start', key: 'type' },
  { title: 'Mini', align: 'start', key: 'mini' },
  { title: 'Nation', align: 'start', key: 'nation' },
]

export const data = [
  {
    main: '༺ঔৣ Tam★Leঔৣ࿐',
    rank: 'R5',
    hq: '',
    type: 'All',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'LeeLyxX',
    rank: 'R4',
    hq: 45,
    type: 'Rider',
    mini: 'NA',
    nation: 'MY',
  },
  {
    main: '❁AzelealoveAsher❁',
    rank: 'R4',
    hq: 44,
    type: 'All',
    mini: '❁AzelealoveAsherN❁',
    nation: 'SG',
  },
  {
    main: 'ᶺᶳᶺ Gizmo',
    rank: 'R4',
    hq: 44,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺ SöDA',
    rank: 'R4',
    hq: 44,
    type: 'Rider',
    mini: 'ᶺᶳᶺ ɱini SöDA',
    nation: 'JPN',
  },
  {
    main: 'Rachel CutCut',
    rank: 'R4',
    hq: 43,
    type: 'Rider',
    mini: 'Rachel Cutter',
    nation: 'SG',
  },
  {
    main: '(˘-˘)sωεεt isle',
    rank: 'R4',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'SG',
  },
  {
    main: 'ᶺᶳᶺ Scarlet-y',
    rank: 'R4',
    hq: 42,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Chubby Unicorn',
    rank: 'R3',
    hq: 44,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺ YakItori',
    rank: 'R3',
    hq: 43,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༺༒クーマ神༒༻',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '˚₊̥Säყä˚₊̥',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Mochito',
    rank: 'R2',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'EURO',
  },
  {
    main: 'ঔৣ༆Gol☆Kichi༆ঔ',
    rank: 'R4',
    hq: 41,
    type: 'Fighter',
    mini: 'mini gol',
    nation: 'JPN',
  },
  {
    main: '★國泰建設★',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'TW',
  },
  {
    main: '༺ༀ.KURUMI.ༀ༻',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'kurumiの2号機.༻',
    nation: 'JPN',
  },
  {
    main: 'Elon Mask',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'KOR',
  },
  {
    main: 'happyme now',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'UNIMO',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ pico',
    rank: 'R3',
    hq: 41,
    type: 'Shooter',
    mini: 'ᶺᶳᶺ pico mini',
    nation: 'JPN',
  },
  {
    main: '༺༒D.TAKESHI༒༻',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: "takeshi's SUB",
    nation: 'JPN',
  },
  {
    main: 'ฅLёёchฅ',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༄༂ƙUMꍏR',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'CAN',
  },
  {
    main: '༺✠T༒T✠༻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: '༺T༒T༻',
    nation: 'VN',
  },
  {
    main: 'kabigon★☆',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'kabigonsub',
    nation: 'JPN',
  },
  {
    main: '✯꧁MinioN꧂✯',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: '➷Minion 2.0 ᥫ᭡',
    nation: 'TBC',
  },
  {
    main: 'Sǝαɲ乙',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'NA',
  },
  {
    main: 'ᶺᶳᶺ Λяѕєη',
    rank: 'R4',
    hq: 40,
    type: 'Rider',
    mini: 'Λяѕєη',
    nation: 'EURO',
  },
  {
    main: '༺Diễm Mai༻',
    rank: 'R4',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ Cooper',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'ᶺᶳᶺ cooper',
    nation: 'TW',
  },
  {
    main: 'ᶺᶳᶺ マウmäw',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'ᶺᶳᶺ マウmaw_baby.',
    nation: 'JPN',
  },
  {
    main: '☞ROYAL✰◔◡◔✰',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'Trinity(とりにてぃ)',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༺ʍαℓ༻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: '༺ʍąℓ༻',
    nation: 'MY',
  },
  {
    main: '•✿•Cẩm Tú•✿•',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '⋆☽✶Levina✶☾⋆',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: '༒OMG༒',
    nation: 'THAI',
  },
  {
    main: 'Zombie Slayer ♡',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'Đậu Lướt Ván.',
    nation: 'USA/VN',
  },
  {
    main: '༄ঔ༒sunny༒ঔ࿐',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Haram ✧˖°. ♪',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'KOR',
  },
  {
    main: '廴ᴋᴇɴᴾᴿᴼシ404',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'Teyan.Ⓓ.Samurai',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'Teyan.D.Gunshi',
    nation: 'JPN',
  },
  {
    main: 'kuno-ichino',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'kuno-ichino (nino)',
    nation: 'JPN',
  },
  {
    main: 'мαѕтєявαιт',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'Bait',
    nation: 'SG',
  },
  {
    main: 'ᶺᶳᶺ Ӱӓй 幻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '口neSie',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'SG',
  },
  {
    main: 'WarCmdr40Fighters',
    rank: 'R1',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'SG',
  },
  {
    main: 'Xá xị',
    rank: 'R4',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ཌༀ۝VICTOR۝ༀད',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: '༺ MILO ༻',
    nation: 'THAI',
  },
  {
    main: 'ITTO☆',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: '☆Itooコーヒー☆',
    nation: 'VN',
  },
  {
    main: '☞╯ƙє√ɨɲ︵☆',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'WOLF -◣⎽⃢◢ ᨼ ᩚ',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '.BERLIAN',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'INDO',
  },
  {
    main: '-Vui Vẻ-',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'edkhtan',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'MY',
  },
  {
    main: 'TínhGià',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'TínhGià.Mini',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ Zen_ou',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '⍣⃝ KAIDO⍣⃝',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'INDO',
  },
  {
    main: '꧁༺ LÊ TÙNG ꧂',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'Lê Tùng 9',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺÐařŧhŽaža',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'EURO',
  },
  {
    main: '˚.♡ʂᶙȵṏ♡.˚',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: '☆suno☆',
    nation: 'JPN',
  },
  {
    main: '༺Adidas Gazelle༻',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'Spawn 4 Sale',
    rank: 'R2',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '꧁༺AFK༻꧂.',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'barbiequinn',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺMiru(ಠہಠ)',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'KOR',
  },
  {
    main: 'boondock❁saint',
    rank: 'R2',
    hq: 31,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '◣_◢ Panda_ꓘſ',
    rank: 'R3',
    hq: 27,
    type: 'Rider',
    mini: 'NA',
    nation: 'TBC',
  },
  {
    main: 'SP...',
    rank: 'R3',
    hq: 24,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
]
