export const headers = [
  {
    title: 'Rank',
    align: 'start',
    sortable: false,
    key: 'rank',
    width: '65px',
  },
  { title: 'Main', align: 'start', key: 'main' },
  { title: 'HQ', align: 'start', key: 'hq' },
  { title: 'Type', align: 'start', key: 'type' },
  { title: 'Mini', align: 'start', key: 'mini' },
  { title: 'Nation', align: 'start', key: 'nation' },
]

export const data = [
  {
    main: '༺ঔৣ Tam★Leঔৣ࿐',
    rank: 'R5',
    hq: 45,
    type: 'All',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '— Coca —',
    rank: 'R4',
    hq: 45,
    type: 'Rider',
    mini: 'Xá xị',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ SöDA',
    rank: 'R4',
    hq: 45,
    type: 'Rider',
    mini: 'ᶺᶳᶺ ɱini SöDA',
    nation: 'JPN',
  },
  {
    main: '༺Itachi❖Uchiha༻',
    rank: 'R4',
    hq: 45,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'LeeLyxX',
    rank: 'R4',
    hq: 45,
    type: 'Rider',
    mini: 'NA',
    nation: 'MY',
  },
  {
    main: 'ɢᴜᴄᴄɪ',
    rank: 'R4',
    hq: 45,
    type: 'All',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'Ɓaϻ Ɓaϻ',
    rank: 'R4',
    hq: 45,
    type: 'All',
    mini: 'ຣƥäņƙŷ',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺ Gizmo',
    rank: 'R4',
    hq: 44,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '❁AzelealoveAsher❁',
    rank: 'R4',
    hq: 44,
    type: 'All',
    mini: '❁AzelealoveAsherN❁',
    nation: 'SG',
  },
  {
    main: 'ᶺᶳᶺ Yakltori',
    rank: 'R3',
    hq: 44,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Rachel CutCut',
    rank: 'R4',
    hq: 43,
    type: 'Rider',
    mini: 'Rachel Cutter',
    nation: 'SG',
  },
  {
    main: 'ᶺᶳᶺ Scarlet-y',
    rank: 'R4',
    hq: 43,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Emma♡エマ',
    rank: 'R3',
    hq: 43,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༺༒クーマ神༒༻',
    rank: 'R3',
    hq: 43,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Sweet isle',
    rank: 'R4',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'SG',
  },
  {
    main: 'boondock❁saınt',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'happyme now',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'Denmark',
  },
  {
    main: 'UNIMO',
    rank: 'R3',
    hq: 42,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺ pico',
    rank: 'R3',
    hq: 42,
    type: 'Shooter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺ Säყä',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺ ULIULI',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '_小黑黑黑啊',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: 'Figgin',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'Lazy Lemon',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'HKG',
  },
  {
    main: 'Panda(♡˙³˙)panda',
    rank: 'R3',
    hq: 41,
    type: 'Shooter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Wallaby おじさん',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ฅLёёchฅ',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༄ঔ༒sunny༒ঔ࿐',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༄༂ ƙUMꍏR Sale',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'CAN',
  },
  {
    main: '༺ༀ.KURUMI.ༀ༻',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'kurumiの2号機.༻',
    nation: 'JPN',
  },
  {
    main: '✿ＳＮＯＷ✿',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '★REBEL★',
    rank: 'R2',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'IM SWORD',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '༺Diễm Mai༻',
    rank: 'R4',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ Λяѕєη',
    rank: 'R4',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'EURO',
  },
  {
    main: '.BERLI',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'INDO',
  },
  {
    main: 'edkhtan',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'NA',
    nation: 'MY',
  },
  {
    main: 'kabigon★☆',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'kuno-ichino',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'lakposht',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: 'Queen Niapatra.',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'UK',
  },
  {
    main: 'Shagg N BaitMASTER',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'Sǝαɲ乙',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'Teyan.Ⓓ.Samurai',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Trinity(とりにてぃ)',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Zombie Slayer ♡',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '~Kalkin~',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'мαѕтєявαιт',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'NA',
    nation: 'SG',
  },
  {
    main: '༺sᴡeetყ ʍäℓ༻',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'MY',
  },
  {
    main: '༺✠T༒T✠༻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ཌༀ۝VICTOR۝ༀད',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'THA',
  },
  {
    main: 'ᴵᴬᴹ ＨＡＤＥＳ',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺ Cooper',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'ᶺᶳᶺ cooper',
    nation: 'TW',
  },
  {
    main: 'ᶺᶳᶺ Ӱӓй 幻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺ マウmäw',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺHaram ⋰˚☆',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'KOR',
  },
  {
    main: 'Ṭ-Đüɓɓź',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '•✿•Cẩm Tú•✿•',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '⋆☽✶Levina✶☾⋆',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'THA',
  },
  {
    main: '░M░I░L░L░',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '★͡Phuc',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '☞╯ƙє√ɨɲ︵☆',
    rank: 'R3',
    hq: 40,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'QUEENDEVIL',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: '✯꧁MinioN꧂✯',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: '廴ᴋᴇɴᴾᴿᴼシ404',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '-Vui Vẻ-',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ITTO☆~_~ ☆',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'Manjuice',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: 'Missiℓє',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: '',
  },
  {
    main: 'Vegeta Saiyan',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'WOLF -◣⎽⃢◢ ᨼ ᩚ',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '˚.♡ʂᶙȵṏ♡.˚',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༺ༀHằng_Nhím ༀ༻',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ Zen_ou',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺbarbiequinn',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺMiru(ಠہಠ)',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'KOR',
  },
  {
    main: '⍣⃝ KAIDO⍣⃝',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'IDN',
  },
  {
    main: '꧁༺ LÊ TÙNG ꧂',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '꧁༺AFK༻꧂.',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ŞɆӾɎ Ş₦ł₱ɆR',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '⊱❀⊰ CELINE ⊱❀⊰',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'Đậu Lướt Ván.',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺÐařŧhŽaža',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'NothingbutLatte',
    rank: 'R3',
    hq: 35,
    type: 'Shooter',
    mini: 'NA',
    nation: 'TW',
  },
  {
    main: 'ɱɛཞ',
    rank: 'R3',
    hq: 34,
    type: 'Fighter',
    mini: 'ɱ♡',
    nation: '',
  },
  {
    main: '༺✿ᴀᴠɪʟᴀ✿༻',
    rank: 'R3',
    hq: 34,
    type: 'Rider',
    mini: 'NA',
    nation: 'IDN',
  },
  {
    main: 'ᴅɪᴏʀ',
    rank: 'R3',
    hq: 34,
    type: 'Fighter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '♡Rhaenyra♡',
    rank: 'R3',
    hq: 34,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: '♡A♡RT♡E♡M♡IS♡',
    rank: 'R3',
    hq: 31,
    type: 'Rider',
    mini: 'NA',
    nation: 'MEX',
  },
]
