export const headers = [
  {
    title: 'Rank',
    align: 'start',
    sortable: false,
    key: 'rank',
    width: '65px',
  },
  { title: 'Main', align: 'start', key: 'main' },
  { title: 'HQ', align: 'start', key: 'hq' },
  { title: 'Type', align: 'start', key: 'type' },
  { title: 'Mini', align: 'start', key: 'mini' },
  { title: 'Nation', align: 'start', key: 'nation' },
]

export const data = [
  {
    main: '༺ঔৣ Tam★Leঔৣ࿐',
    rank: 'R5',
    hq: 45,
    type: 'All',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '❁AzelealoveAsher❁',
    rank: 'R4',
    hq: 43,
    type: 'All',
    mini: '❁AzelealoveAsherN❁',
    nation: 'SG',
  },
  {
    main: 'ᶺᶳᶺ Gizmo',
    rank: 'R4',
    hq: 43,
    type: 'Rider',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺ SöDA',
    rank: 'R4',
    hq: 43,
    type: 'Rider',
    mini: 'ᶺᶳᶺ ɱini SöDA',
    nation: 'JPN',
  },
  {
    main: '༺༒dark༒༻',
    rank: 'R4',
    hq: 43,
    type: 'All',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'sᴘᴀᴡɴ',
    rank: 'R4',
    hq: 42,
    type: 'Shooter',
    mini: 'Small Spawn',
    nation: 'USA',
  },
  {
    main: '༺༒lien༒༻',
    rank: 'R3',
    hq: 42,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Rachel CutCut',
    rank: 'R4',
    hq: 42,
    type: 'Rider',
    mini: 'Rachel Cutter',
    nation: 'SG',
  },
  {
    main: 'いきなり♡だいふく',
    rank: 'R4',
    hq: 41,
    type: 'Fighter',
    mini: '大福3150',
    nation: 'JPN',
  },
  {
    main: 'ঔৣ༆Gol☆Kichi༆ঔ',
    rank: 'R4',
    hq: 41,
    type: 'Fighter',
    mini: 'mini gol',
    nation: 'JPN',
  },
  {
    main: '~Mochito~',
    rank: 'R4',
    hq: 41,
    type: 'Rider',
    mini: "Moch's",
    nation: 'EURO',
  },
  {
    main: 'Coca',
    rank: 'R4',
    hq: 41,
    type: 'Rider',
    mini: 'Xá xị',
    nation: 'VN',
  },
  {
    main: '.¥ Gemini ¥.',
    rank: 'R3',
    hq: 41,
    type: 'Shooter',
    mini: ' ᶺᶳᶺ Miru(~)',
    nation: 'VN/KOR',
  },
  {
    main: 'ᶺᶳᶺ Scarlet-y',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺULIULI',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '˚₊̥Säყä˚₊̥',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: '꒰ঌSena໒꒱',
    nation: 'JPN',
  },
  {
    main: 'Sweet isle',
    rank: 'R3',
    hq: 41,
    type: 'Rider',
    mini: 'Mini Sweetstorm',
    nation: 'SG',
  },
  {
    main: '★國泰建設★',
    rank: 'R1',
    hq: 41,
    type: 'Rider',
    mini: 'NA',
    nation: 'TW',
  },
  {
    main: 'CHALLENGER',
    rank: 'R3',
    hq: 41,
    type: 'Fighter',
    mini: 'NA',
    nation: 'NL',
  },
  {
    main: 'Brassiere',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'Brassiere less',
    nation: 'JPN',
  },
  {
    main: '༺ༀ.KURUMI.ༀ༻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'kurumiの2号機.༻',
    nation: 'JPN',
  },
  {
    main: '༺✠T༒T✠༻',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: '༺T༒T༻',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ pico',
    rank: 'R3',
    hq: 41,
    type: 'Shooter',
    mini: 'ᶺᶳᶺ pico mini',
    nation: 'JPN',
  },
  {
    main: 'kabigon★☆',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'kabigonsub',
    nation: 'JPN',
  },
  {
    main: '✯꧁MinioN꧂✯',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: '➷Minion 2.0 ᥫ᭡',
    nation: 'TBC',
  },
  {
    main: 'Sean 乙',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'NA',
  },
  {
    main: 'PSYCHO☆7',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'NA',
  },
  {
    main: '༄༂ASA_Huy ༂࿐',
    rank: 'R2',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'WarCmdr40Fighters',
    rank: 'R1',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'SG',
  },
  {
    main: 'Λяѕєη',
    rank: 'R4',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: 'EURO',
  },
  {
    main: '.༺Diễm Mai ༻.',
    rank: 'R4',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ マウmaw',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'ᶺᶳᶺ マウmaw_baby.',
    nation: 'JPN',
  },
  {
    main: 'ROYAL',
    rank: 'R3',
    hq: 40,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: '~Cooper~',
    rank: 'R3',
    hq: 40,
    type: 'Fighter',
    mini: 'NA',
    nation: '',
  },
  {
    main: 'Trinity(とりにてぃ)',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: '༺ʍαℓ༻',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: '༺ʍąℓ༻',
    nation: 'MY',
  },
  {
    main: '•✿•Cẩm Tú•✿•',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: '✿•Cẩm Tú•✿',
    nation: 'VN',
  },
  {
    main: '⋆☽✶Levina✶☾⋆',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: '༒OMG༒',
    nation: 'THAI',
  },
  {
    main: 'Zombie Slayer ♡',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: '༺lil zom༻',
    nation: 'USA',
  },
  {
    main: '༄ঔ༒sunny༒ঔ࿐',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'ᶺᶳᶺ Thanh Nguyễn',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'Haram ✧˖°. ♪',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'KOR',
  },
  {
    main: 'ཌༀ۝VICTOR۝ༀད',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: '༺ MILO ༻',
    nation: 'THAI',
  },
  {
    main: '☆Itto~_~Coffe☆',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: '☆Itooコーヒー☆',
    nation: 'VN',
  },
  {
    main: '☞╯ƙє√ɨɲ︵☆',
    rank: 'R3',
    hq: 39,
    type: 'Shooter',
    mini: '~Kevin~',
    nation: 'VN',
  },
  {
    main: '廴ᴋᴇɴᴾᴿᴼシ404',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'Teyan.D.Samurai',
    rank: 'R3',
    hq: 39,
    type: 'Fighter',
    mini: 'Teyan.D.Gunshi',
    nation: 'JPN',
  },
  {
    main: 'NIGHTWOLF1',
    rank: 'R3',
    hq: 39,
    type: 'Rider',
    mini: 'NA',
    nation: '',
  },
  {
    main: '.BERLIAN',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: '.RATU BERLIAN',
    nation: 'INDO',
  },
  {
    main: '-Vui Vẻ-',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'edkhtan',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'MY',
  },
  {
    main: 'TuấnPhương88',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'TínhGià',
    rank: 'R3',
    hq: 38,
    type: 'Fighter',
    mini: 'TínhGià.Mini',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺ Zen_ou',
    rank: 'R3',
    hq: 38,
    type: 'Fighter',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'KAIDO',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'INDO',
  },
  {
    main: '★ᴍʀ ᴅ ᴀ ʀ ᴋ★',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: '꧁༺ LÊ TÙNG ꧂',
    rank: 'R3',
    hq: 38,
    type: 'Fighter',
    mini: 'Lê Tùng 9',
    nation: 'VN',
  },
  {
    main: 'ᶺᶳᶺÐařŧhŽaža',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'EURO',
  },
  {
    main: '♡suno♡',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: '☆suno☆',
    nation: 'JPN',
  },
  {
    main: 'yan幻SR',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'Acid Black Cherry♡',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'NA',
    nation: 'JPN',
  },
  {
    main: 'kunoichi-no-ichino',
    rank: 'R3',
    hq: 38,
    type: 'Rider',
    mini: 'kunoichi-no-ichino-2',
    nation: 'JPN',
  },
  {
    main: 'мαѕтєявαιт',
    rank: 'R3',
    hq: 38,
    type: 'Shooter',
    mini: 'NA',
    nation: '',
  },
  {
    main: '꧁༺AFK༻꧂.',
    rank: 'R3',
    hq: 37,
    type: 'Shooter',
    mini: '꧁༺. BụIcÁm.༻꧂',
    nation: 'VN',
  },
  {
    main: 'barbiequinn',
    rank: 'R3',
    hq: 37,
    type: 'Shooter',
    mini: 'NA',
    nation: 'USA',
  },
  {
    main: 'ᶺᶳᶺ NARCISO',
    rank: 'R3',
    hq: 29,
    type: 'Rider',
    mini: 'NA',
    nation: 'EURO',
  },
  {
    main: '◣_◢ Panda_ꓘſ',
    rank: 'R3',
    hq: 27,
    type: 'Rider',
    mini: 'NA',
    nation: 'TBC',
  },
  {
    main: 'NgọcDuySàiGòn',
    rank: 'R2',
    hq: 27,
    type: 'Rider',
    mini: 'NA',
    nation: 'VN',
  },
  {
    main: 'SP…',
    rank: 'R3',
    hq: 24,
    type: 'Shooter',
    mini: 'NA',
    nation: 'VN',
  },
]
